name: Actions Workflow

on: 
  push:
    branches:
      - master
      - '/feature/*' # Matches feature/featA, feature/featB, doesnt match feature/feat/featA
      - '/feature/**'  # Matches feature/feat/featA,
    # branches-ignore:
    #   - ""
    tags:
      - v1.*
    paths:
      - '**.js'
    # paths-ignore:
    #   - ""
  pull_request:
    types: 
      - closed
      - assigned
      - opened
      - reopened
  repository_dispatch:
    types:
      - build
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
      
jobs:
  run-gitbub-actions:
   runs-on: ubuntu-latest
   steps:
      - name: Repo Dispatch Payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: List files
        run: |
          pwd
          ls
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
      - name: Simple javascript action
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: Codetraxx 
      - name: Greeting time
        run: echo "${{ steps.greet.outputs.time }}"
     